#!/usr/bin/env bash
#
# fatura-convert - Converte PDF da fatura em PNG.
#
# Site      : https://github.com/linuxjeff
# Autor     : Jefferson Santana <computadores.rp@gmail.com>
#
# -----------------------------------------------------------------------------
#   Descrição: Utilizando o pacote poppler-utils para converter o PDF da fatura
#              em um arquivo PNG.
#
#   Exemplos:
#
# -----------------------------------------------------------------------------
#
#
# Histórico:
#
#  v0.0.1 26-08-2023, Jefferson Santana
#   - Versão inicial.
#  v0.0.2 27-08-2023, Jefferson Santana
#   - Cópiando o comando principal do .zshrc.
#   - Feito algumas alterações no comando, pois no .zshrc é usado alias.
#   - Colocado as variáveis do nome do arquivos.
#   - Foi trocado o nome do arquivo de fature-convert para fatura-convert.
#
# Licença: MIT.
#

# Variáveis
NOMEDOARQUIVO="fatura"
NOMEDOCAMINHO="$HOME/Downloads/"

pdftoppm -png "$NOMEDOCAMINHO""$NOMEDOARQUIVO".pdf "$NOMEDOCAMINHO""$NOMEDOARQUIVO"
